# Generated by Django 5.0.6 on 2024-05-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('second_name', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('fit_criteries', models.IntegerField()),
                ('java', models.BooleanField()),
                ('cpp', models.BooleanField()),
                ('go', models.BooleanField()),
                ('python', models.BooleanField()),
                ('javascript', models.BooleanField()),
                ('css', models.BooleanField()),
                ('sql', models.BooleanField()),
            ],
        ),
    ]
